description: "blazenet model for pose 2d estimation with freihand"
dataset:
  data_dir: data/freihand
  dataset_name: datasets.freihand.dataset_utils.HandPoseDataset
  sample_image_idx: 10
  is_sample_training: True
  use_augmented: False
  use_evaluation: False
  test_size: 0.1
training_details:
  trainer: trainers.blazenet_trainer_v3.Pose2DTrainer
  epochs: 10000
  batch_size: 32
  optimizer: torch.optim.Adam
  learning_rate: 0.01
  num_workers: 8
  shuffle: True
  scheduler: torch.optim.lr_scheduler.ReduceLROnPlateau
  scheduler_factor: 0.5
  scheduler_patience: 10
  scheduler_verbose: True
  scheduler_threshold: 0.0001
  device: cuda
  loss_file: exp/loss_info.txt
  model_file: exp/model
model:
  model_name: models.blazenet_model.Pose2dModel
  model_file: ""
  n_keypoints: 21
  raw_image_size: 256
  model_img_size: 64
test:
  test_class: datasets.freihand.test_dataset.TestDataset
  model_file: exp/model_1.pth
  device: cpu
