description: "blazenet 2d with resnet34 resolution 128 decoder channels 21 residual blocks on decoder on ntu and freihand dataset"
dataset:
  data_dir: data/freihand
  dataset_name: datasets.freihand.dataset_utils.HandPoseDataset
  sample_image_idx: 10
  is_sample_training: True
  use_augmented: False
  use_evaluation: False
  test_size: 0.1
training_details:
  trainer: trainers.blazenet_trainer.Pose2DTrainer
  epochs: 200
  batch_size: 32
  optimizer: torch.optim.Adam
  learning_rate: 0.001
  num_workers: 8
  shuffle: True
  scheduler: torch.optim.lr_scheduler.ReduceLROnPlateau
  scheduler_factor: 0.5
  scheduler_patience: 5
  scheduler_verbose: True
  scheduler_threshold: 0.0001
  device: cuda
  loss_file: exp/loss_info.txt
  model_file: exp/model
  bg_imgs_dir: data/bg_imgs
model:
  model_name: models.blazenet_model_v6.Pose2dModel
  model_file: ""
  n_keypoints: 21
  raw_image_size: 256
  model_img_size: 128
test:
  test_class: datasets.freihand.test_dataset.TestDataset
  model_file: exp/model_1.pth
  device: cpu
