dataset:
  images_dir: data/real_world_testset/images
  camera_param_file: data/real_world_testset/params.mat
  global_pose3d_gt_file: data/real_world_testset/pose_gt.mat
  global_mesh_gt_dir: data/real_world_testset/real_hand_3D_mesh
  val_cams_file: ./data/synthetic_train_val/3D_labels/val-camera.txt
  sample_image_file: data/real_world_testset/images/00018.jpg
  dataset_name: datasets.ntu.dataset_utils.HandPoseDataset
training_details:
  trainer: "trainers.hourglass_trainer.Pose2DTrainer"
  epochs: 10000
  batch_size: 1
  optimizer: "torch.optim.Adam"
  learning_rate: 0.01
  num_workers: 4
  shuffle: True
  scheduler: torch.optim.lr_scheduler.ReduceLROnPlateau
  scheduler_factor: 0.5
  scheduler_patience: 3
  scheduler_verbose: True
  scheduler_threshold: 0.0001
  device: cuda
  loss_file: exp/loss_info.txt
  model_file: exp/model
model:
  model_name: "models.hourglass_model.Pose2dModel"
  model_file: ""
  n_keypoints: 21
  raw_image_size: 256
  model_img_size: 64
test:
  test_class: datasets.ntu_real.test_dataset.TestDataset
  model_file: exp/model_1.pth
  device: cpu
