description: "blazenet model for pose 3d estimation residual blocks on freihand"
dataset:
  data_dir: data/freihand
  dataset_name: datasets.freihand.dataset_utils.HandPoseDataset
  sample_image_idx: 10
  is_sample_training: True
  use_augmented: False
  use_evaluation: True
  test_size: 0.1
training_details:
  trainer: trainers.blazenet3d_trainer.Pose3DTrainer
  epochs: 30
  batch_size: 32
  optimizer: torch.optim.Adam
  learning_rate: 0.001
  num_workers: 8
  shuffle: True
  scheduler: torch.optim.lr_scheduler.ReduceLROnPlateau
  scheduler_factor: 0.5
  scheduler_patience: 5
  scheduler_verbose: True
  scheduler_threshold: 0.0001
  device: cuda
  loss_file: exp/loss_info.txt
  model_file: exp/model
  is_freeze_pose2d: True
  bg_imgs_dir: data/bg_imgs
model:
  model_name: models.blazenet_model_3d_v2_5.Pose3dModel
  model_file: ""
  n_keypoints: 21
  raw_image_size: 256
  model_img_size: 128
test:
  test_class: datasets.freihand.test_dataset.TestDataset
  model_file: exp/model_1.pth
  device: cpu
  dataset_name: freihand
