description: "blazenet model for pose 3d estimation residual blocks on freihand"
dataset:
  images_dir: data/synthetic_train_val/images
  camera_param_file: ./data/synthetic_train_val/3D_labels/camPosition.txt
  global_pose3d_gt_file: ./data/synthetic_train_val/3D_labels/handGestures.txt
  global_mesh_gt_dir: ./data/synthetic_train_val/hand_3D_mesh
  val_cams_file: ./data/synthetic_train_val/3D_labels/val-camera.txt
  sample_image_file: data/synthetic_train_val/images/l21/cam21/handV2_rgt01_specTest5_gPoses_ren_25cRrRs_l21_cam21_.0492.png
  dataset_name: datasets.ntu.dataset_utils_v2.HandPoseDataset
  test_size: 0.1
training_details:
  trainer: trainers.blazenet3d_trainer.Pose3DTrainer
  epochs: 15
  batch_size: 32
  optimizer: torch.optim.Adam
  learning_rate: 0.001
  num_workers: 8
  shuffle: True
  scheduler: torch.optim.lr_scheduler.ReduceLROnPlateau
  scheduler_factor: 0.5
  scheduler_patience: 5
  scheduler_verbose: True
  scheduler_threshold: 0.0001
  device: cuda
  loss_file: exp/loss_info.txt
  model_file: exp/model
  is_freeze_pose2d: True
  bg_imgs_dir: data/bg_imgs
model:
  model_name: models.blazenet_model_3d_v1_2.Pose3dModel
  model_file: ""
  n_keypoints: 21
  raw_image_size: 256
  model_img_size: 128
test:
  test_class: datasets.ntu.test_dataset.TestDataset
  model_file: exp/model_1.pth
  device: cpu
  dataset_name: ntu
